name: find_on_campus
description: "A lost and found platform for campus communities."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.0  # Loading indicators
  image_picker: ^1.0.7     # For picking images when reporting items
  
  # Authentication
  google_sign_in: ^6.2.1   # For Google authentication
  firebase_auth: ^5.5.1   # Firebase authentication
  
  # Data Storage
  cloud_firestore: ^5.6.5  # Cloud Firestore database
  firebase_storage: ^12.4.4  # For storing images
  firebase_core: ^3.12.1    # Firebase core functionality
  
  # State Management
  provider: ^6.1.4        # State management
  
  # Utilities
  intl: ^0.20.2           # For date formatting
  cached_network_image: ^3.3.1  # For efficiently loading images
  uuid: ^4.3.3            # For generating unique IDs
  geolocator: ^13.0.3     # For location services
  url_launcher: ^6.2.5    # For launching URLs
  
  # Notifications
  firebase_messaging: ^15.2.4  # For push notifications
  flutter_local_notifications: ^19.0.0  # For local notifications

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Uncomment to add assets when we have them
  # assets:
  #   - assets/images/
  #   - assets/icons/
